#FROM gcr.io/clusterekaitz/source:exist-base
FROM openjdk:8-jre-alpine

COPY lib /lib

COPY SDE.jar /

ENV MACHINE_ID=NULL

ENV RANGE=60

ENV KAFKA_KEY=app1-source-exist

WORKDIR /

CMD ["java", "-jar", "SDE.jar"]