apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aplicaciones.misrecursos.aplicacion
spec:
  group: misrecursos.aplicacion
  versions:
    - name: v1alpha1
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                componentes:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
    - name: v1alpha2
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [componentes,image,replicas]
              properties:
                componentes:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status: 
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
    - name: v1alpha3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [componentes,replicas]
              properties:
                componentes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      previous:
                        type: string
                      next:
                        type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status:
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
#    - name: v1alpha4
#      served: false
#      storage: false
#      schema:
#        openAPIV3Schema:
#          type: object
#          properties:
#            spec:
#              type: object
#              required: [ componentes,replicas ]
#              properties:
#                componentes:
#                  type: array
#                  items:
#                    type: object
#                    properties:
#                      componente:
#                        x-kubernetes-embedded-resource: true
#                replicas:
#                  type: integer
#                  minimum: 1
#                  maximum: 10
#            status:
#              type: object
#              properties:
#                replicas:
#                  type: integer
#      subresources:
#        status: { }
#        scale:
#          specReplicasPath: .spec.replicas
#          statusReplicasPath: .status.replicas
  scope: Namespaced
  names:
    plural: aplicaciones
    singular: aplicacion
    kind: Aplicacion