apiVersion: ehu.gcis.org/v1alpha1
kind: Asset
metadata:
  name: asset-cr-processing-1
spec:
  name: asset-1
  deploy: True
  assemblystations:
    - name: assembly-station-1
      deploy: True
      applications:
        - name: data-processing-app-1-model-2
          deploy: True
          replicas: 1
          components:
            - name: data-processing-1-exist
              image: ekaitzhara/source-v2:source-exist
              flowConfig:
#                previous: none # No es necesario añadir los dos, si no hay previous, no se añade
                next:
                  - name: data-processing-assemblystation
                    IFMHtopic: datos-processing-assembly-oee
              customization:
                - "MACHINE_ID=11"
              permanent: False
            - name: data-processing-assemblystation
              image: ekaitzhara/processing-v2:assembly-station-v2.2
              flowConfig:
                previous:
                  - name: data-processing-1-exist
                    IFMHtopic: datos-processing-assembly-oee
                next:
                  - name: data-processing-1-influx
                    IFMHtopic: datos-processing-1-assembly-oee-influx
              customization:
                - "LIMIT=72"
              permanent: True
            - name: data-processing-1-influx
              image: ekaitzhara/sink-v2:sink-influx
              flowConfig:
                previous:
                  - name: data-processing-assemblystation
                    IFMHtopic: datos-processing-1-assembly-oee-influx
#                next: none
              permanent: False  # Hay que meterlo siempre? (deberia ponerse en required del CRD) O si no se mete, el controlador lo pone a False?