FROM tomcat:jdk8-openjdk

#################################################
# Copy required files
#################################################

COPY CC.jar /dockerfiles/

COPY Dockerfile2.tar.gz /dockerfiles/

COPY Dockerfile_2 /dockerfiles/

COPY credentials.json /dockerfiles/

COPY clusterekaitz-9111417e6259.json /dockerfiles/

#################################################
# Install Docker to build images
#################################################

#RUN apt-get update

#RUN apt-get install -y docker.io

#################################################
# Install gcloud to push images to repository
#################################################

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

RUN apt-get update && apt-get install -y google-cloud-sdk

WORKDIR /dockerfiles/

#################################################
# Configure gcloud project to allow the uploads
#################################################

#RUN gcloud auth activate-service-account ekaitz@clusterekaitz.iam.gserviceaccount.com --key-file=credentials.json
#RUN gcloud auth activate-service-account ekaitzhara16@gmail.com --key-file=clusterekaitz-9111417e6259.json

#RUN gcloud config set project clusterekaitz

#RUN gcloud auth configure-docker

EXPOSE 8080

CMD ["catalina.sh", "run"]

