FROM gcr.io/clusterekaitz/processing:base

RUN pip install influxdb-client

COPY pqp.py .

COPY influxAPI.py .

ENV FLASK_APP=pqp.py

ENV FUNCTION=processingOEE

ENV inPort=TDBStation

ENV outPort=TStationOEE

ENV LIMIT=67

CMD flask run --host=0.0.0.0
