apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: assemblystation-controller
  name: assemblystation-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblystation-controller
  template:
    metadata:
      labels:
        app: assemblystation-controller
    spec:
      containers:
      - env:
        - name: LEVEL_NAME
          value: assemblystation
        - name: LEVEL_NAME_PLURAL
          value: assemblystations
        - name: LOWER_LEVEL_NAME
          value: application
        - name: LOWER_LEVEL_NAME_PLURAL
          value: applications
        - name: HIGHER_LEVEL_NAME
          value: asset
        - name: HIGHER_LEVEL_NAME_PLURAL
          value: assets
        image: ekhurtado/gcis-fog:generic_app_management_level_controller-v4.0
        imagePullPolicy: Always
        name: assemblystation-controller
        ports:
        - containerPort: 80
      nodeSelector:
        node-role.kubernetes.io/master: 'true'
