apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-controller-component
rules:
- apiGroups:
  - ehu.gcis.org
  resources:
  - components
  - components/status
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - delete
- apiGroups:
  - ehu.gcis.org
  resources:
  - applications
  - applications/status
  verbs:
  - get
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - post
  - put
  - patch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - post
  - put
  - patch
  - create
  - update
- apiGroups:
  - ''
  resources:
  - events
  - configmaps
  verbs:
  - watch
  - create
  - update
  - get
