#FROM gcr.io/clusterekaitz/source:exist-base
FROM openjdk:8-jre-alpine

COPY Source_eXist_lib /Source_eXist_lib

COPY Source_eXist.jar /

ENV MACHINE_ID=NULL

ENV RANGE=60

ENV KAFKA_TOPIC=topico-datos-assembly-oee

ENV KAFKA_KEY=app2-source-exist

WORKDIR /

CMD ["java", "-jar", "Source_eXist.jar"]