apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: componentes.misrecursos.aplicacion
spec:
  group: misrecursos.aplicacion
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [name, image, previous, next]
              properties:
                name:
                  type: string
                image:
                  type: string
                previous:
                  type: string
                next:
                  type: string
                kafkaTopic:
                  type: string
                customization:
                  type: array
                  items:
                    type: string
                permanente:
                  type: boolean
            status:
              type: object
              properties:
                replicas:
                  type: integer
                situation:
                  type: string
      additionalPrinterColumns:
        - jsonPath: .metadata.labels.shortName
          name: Shortname
          description: Name of the component
          type: string
          priority: 0
        - jsonPath: .status.situation
          name: Status
          type: string
          priority: 0 # si es prioridad 0 aparece en la vista estandar
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          priority: 0
        - jsonPath: .spec.kafkaTopic
          name: KafkaTopic
          type: string
          priority: 1 # prioridad 1 solo aparece en la vista ampliada (-o wide)
        - jsonPath: .spec.image
          name: Image
          description: Docker image of the component
          type: string
          priority: 1
        - jsonPath: .status.replicas
          name: Replicas
          type: integer
          priority: 1
#        - jsonPath: .spec.previous
#          name: Previous
#          type: string
#          priority: 1 # prioridad 1 solo aparece en la vista ampliada (-o wide)
#        - jsonPath: .spec.next
#          name: Next
#          type: string
#          priority: 1
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: componentes
    singular: componente
    kind: Componente
    shortNames:
      - comp
