FROM python:3.10-alpine

RUN pip install kubernetes
RUN pip install datetime
RUN pip install pytz

COPY ../CRD/application_definition.yaml /CRD/
COPY ../scripts_python/mi_controlador_aplicaciones.py /
COPY ../scripts_python/tipos.py /

CMD python3 mi_controlador_aplicaciones.py
