FROM python:3.10-alpine

RUN pip install kubernetes
RUN pip install datetime
RUN pip install pytz

COPY ../CRD/component_definition.yaml /CRD/
COPY ../scripts_python/mi_controlador_componentes.py /
COPY ../scripts_python/tipos.py /
CMD python3 mi_controlador_componentes.py
