apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: assemblystations.ehu.gcis.org
spec:
  group: ehu.gcis.org
  names:
    kind: Assemblystation
    plural: assemblystations
    singular: assemblystation
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Readiness of the created resource
      jsonPath: .status.ready
      name: Ready
      priority: 0
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      priority: 0
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              applications:
                items:
                  properties:
                    components:
                      items:
                        properties:
                          customization:
                            items:
                              type: string
                            type: array
                          flowConfig:
                            properties:
                              next:
                                type: string
                              previous:
                                type: string
                            type: object
                          image:
                            type: string
                          inputIFMHtopic:
                            type: string
                          name:
                            type: string
                          outputIFMHtopic:
                            type: string
                          permanent:
                            type: boolean
                        required:
                        - name
                        - image
                        - flowConfig
                        type: object
                      type: array
                    deploy:
                      type: boolean
                    name:
                      type: string
                    replicas:
                      maximum: 10
                      minimum: 1
                      type: integer
                  required:
                  - components
                  - replicas
                  - deploy
                  type: object
                type: array
              deploy:
                type: boolean
              name:
                type: string
            type: object
          status:
            properties:
              applications:
                items:
                  properties:
                    name:
                      type: string
                    status:
                      type: string
                  type: object
                type: array
              ready:
                type: string
              replicas:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
