FROM ekaitzhara/processing-v2:base

RUN pip3 install influxdb-client

RUN pip install kubernetes

COPY pqp.py .

COPY influxAPI.py .

#ENV FLASK_APP=pqp.py

ENV LIMIT=67

#CMD flask run --host=0.0.0.0
CMD python3 pqp.py
