apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: activos.misrecursos.aplicacion
spec:
  group: misrecursos.aplicacion
  names:
    kind: Activo
    plural: activos
    singular: activo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              aplicacions:
                items:
                  properties:
                    componentes:
                      items:
                        properties:
                          image:
                            type: string
                          name:
                            type: string
                          next:
                            type: string
                          permanente:
                            type: boolean
                          previous:
                            type: string
                        type: object
                      type: array
                    desplegar:
                      type: boolean
                    name:
                      type: string
                    replicas:
                      maximum: 10
                      minimum: 1
                      type: integer
                  required:
                  - componentes
                  - replicas
                  - desplegar
                  type: object
                type: array
              desplegar:
                type: boolean
              name:
                type: string
            type: object
          status:
            properties:
              replicas:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
