apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: NombreNivel + 's' + '.misrecursos.aplicacion'
spec:
  group: misrecursos.aplicacion
  versions:
    - name: v1alpha1 #Anadido un parametro para almacenar la aplicacion definida y desplegarla a posteriori.
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                desplegar:
                  type: boolean
                aplicacions: #Problemas con los plurales que no acaban solo en 's'.
                  type: array
                  items:
                    type: object
                    required: [ componentes,replicas,desplegar ]
                    properties:
                      componentes:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            image:
                              type: string
                            previous:
                              type: string
                            next:
                              type: string
                            permanente:
                              type: boolean
                      replicas:
                        type: integer
                        minimum: 1
                        maximum: 10
                      desplegar:
                        type: boolean
                      name:
                        type: string
            status:
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
  scope: Namespaced
  names:
    plural: NombreNivel + 's'
    singular: NombreNivel
    kind: NombreNivel