apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plantas.misrecursos.aplicacion
spec:
  group: misrecursos.aplicacion
  names:
    kind: Planta
    plural: plantas
    singular: planta
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              activos:
                items:
                  properties:
                    aplicacions:
                      items:
                        properties:
                          componentes:
                            items:
                              properties:
                                image:
                                  type: string
                                name:
                                  type: string
                                next:
                                  type: string
                                permanente:
                                  type: boolean
                                previous:
                                  type: string
                              type: object
                            type: array
                          desplegar:
                            type: boolean
                          name:
                            type: string
                          replicas:
                            maximum: 10
                            minimum: 1
                            type: integer
                        required:
                        - componentes
                        - replicas
                        - desplegar
                        type: object
                      type: array
                    desplegar:
                      type: boolean
                    name:
                      type: string
                  type: object
                type: array
              desplegar:
                type: boolean
              name:
                type: string
            type: object
          status:
            properties:
              replicas:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
