apiVersion: misrecursos.aplicacion/v1alpha4
kind: Aplicacion
metadata:
  name: data-processing-app-1-model-2
spec:
  componentes:
    - name: data-processing-1-exist
      image: ekaitzhara/source-v2:source-exist
      flowConfig:
        previous: none
        next: data-processing-assemblystation
      kafkaTopic: datos-processing-1-assembly-oee # TODO El topico deberia ser el mismo para las dos aplicaciones no?
      customization:
        - "MACHINE_ID=11"
      permanente: False
    - name: data-processing-assemblystation
      image: ekaitzhara/processing-v2:assembly-station-v2.2
      flowConfig:
        previous: data-processing-1-exist
        next: data-processing-1-influx     # En este next tendría que haber dos: Influx y OEEevents
      kafkaTopic: datos-processing-assembly-oee  # TODO El topico deberia ser el mismo para esta permanente no?
      customization:
        - "LIMIT=72"
      permanente: True  # En este caso sí es un componente permanente (siempre lo es? o solo cuando participa en más de una app?)
#      permanenteCM: cm-data-processing-assemblystation
    - name: data-processing-1-influx
      image: ekaitzhara/sink-v2:sink-influx
      flowConfig:
        previous: data-processing-assemblystation
        next: none
      kafkaTopic: datos-processing-1-assembly-oee-influx
      permanente: False
#    - name: data-processing-1-oeeevents
#      image: gcr.io/clusterekaitz/application-oee:dataprocessing-oeeevents
#      previous: data-processing-influx
#      next: none
#      permanente: False
  replicas: 1
  desplegar: True