apiVersion: misrecursos.aplicacion/v1alpha4
kind: Aplicacion
metadata:
  name: data-processing-app-2-model-2
spec:
  componentes:
    - name: data-processing-2-exist
      image: ekaitzhara/source-v2:source-exist
      flowConfig:
        previous: none
        next: data-processing-assemblystation
      kafkaTopic: datos-processing-assembly-oee
      customization:
        - "MACHINE_ID=22"
      permanente: False
    - name: data-processing-assemblystation
      image: ekaitzhara/processing-v2:assembly-station-v2.2
      flowConfig:
        previous: data-processing-2-exist
        next: data-processing-2-influx     # En este next tendría que haber dos: Influx y OEEevents
      kafkaTopic: datos-processing-assembly-oee
      customization:
        - "LIMIT=74"
      permanente: True
#      permanenteCM: cm-data-processing-assemblystation
    - name: data-processing-2-influx
      image: ekaitzhara/sink-v2:sink-influx
      flowConfig:
        previous: data-processing-assemblystation
        next: none
      kafkaTopic: datos-processing-2-assembly-oee-influx
      permanente: False
#    - name: data-processing-1-oeeevents
#      image: gcr.io/clusterekaitz/application-oee:dataprocessing-oeeevents
#      previous: data-processing-influx
#      next: none
#      permanente: False
  replicas: 1
  desplegar: True