apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aplicaciones.mis-recursos.aplicacion
spec:
  group: mis-recursos.aplicacion
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                componentes:
                  type: array
                  description: "Componentes que forman la aplicacion."
                  items: 
                    type: Componente
                    properties:
                      spec:
                        type: object
                        properties:
                          name:
                            type: string
                          image:
                            type: string
                            required: true
                replicas:
                  type: integer
                  minimum: 1
  scope: Namespaced
  names:
    plural: aplicaciones
    singular: aplicacion
    kind: Aplicacion