apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: componentes.misrecursos.aplicacion
spec:
  group: misrecursos.aplicacion
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [image, previous, next]
              properties:
                image:
                  type: string
                previous:
                  type: string
                next:
                  type: string
                permanente:
                  type: boolean
            status:
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: componentes
    singular: componente
    kind: Componente