apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aplicaciones.misrecursos.aplicacion
spec:
  group: misrecursos.aplicacion
  versions:
    - name: v1alpha1
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                componentes:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
    - name: v1alpha2
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [componentes,image,replicas]
              properties:
                componentes:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status:
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
    - name: v1alpha3
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [componentes,replicas]
              properties:
                componentes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      previous:
                        type: string
                      next:
                        type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status:
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
    - name: v1alpha4 #Anadido un parametro para almacenar la aplicacion definida y desplegarla a posteriori.
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [ componentes,replicas,desplegar ]
              properties:
                componentes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      previous:
                        type: string
                      next:
                        type: string
                      permanente:
                        type: boolean
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
                desplegar: # Anadido.
                  type: boolean
            status:
              type: object
              properties:
                replicas:
                  type: integer
                componentes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      status:
                        type: string
                ready:
                  type: string
      additionalPrinterColumns:
        - jsonPath: .spec.replicas
          name: Desired Replicas
          type: integer
          priority: 0 # si es prioridad 0 aparece en la vista estandar
        - jsonPath: .status.replicas
          name: Current Replicas
          type: integer
          priority: 0
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          priority: 0
        - jsonPath: .status.ready
          name: Ready
          type: string
          description: Readiness of the created resource
          priority: 0
        - jsonPath: .spec.componentes[*].name
          name: Image
          description: Docker image of the component
          type: string
          priority: 1 # si es prioridad mayor que 1 aparece solo en la vista amplicada (-o wide)
#        - jsonPath: .status.ready
#          name: Ready
#          description: Readiness of the created resource
#          type: string
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
#    - name: v1alpha5
#      served: false
#      storage: false
#      schema:
#        openAPIV3Schema:
#          type: object
#          properties:
#            spec:
#              type: object
#              required: [ componentes,replicas ]
#              properties:
#                componentes:
#                  type: array
#                  items:
#                    type: object
#                    properties:
#                      componente:
#                        x-kubernetes-embedded-resource: true
#                replicas:
#                  type: integer
#                  minimum: 1
#                  maximum: 10
#            status:
#              type: object
#              properties:
#                replicas:
#                  type: integer
#      subresources:
#        status: { }
#        scale:
#          specReplicasPath: .spec.replicas
#          statusReplicasPath: .status.replicas
  scope: Namespaced
  names:
    plural: aplicaciones
    singular: aplicacion
    kind: Aplicacion
    shortNames:
      - app