apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.ehu.gcis.org
spec:
  group: ehu.gcis.org
  versions:
    - name: v1alpha4 # Added a parameter to store the defined application and display it later
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [ components,replicas,deploy ]
              properties:
                name:
                  type: string
                components:
                  type: array
                  items:
                    type: object
                    required: [ name,image,flowConfig ]
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      # FLOWCONFIG 2.0 (para creacion de aplicaciones complejas -> DAGs)
                      flowConfig:
                        type: object
                        properties:
                          previous:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                IFMHtopic:
                                  type: string
                          next:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                IFMHtopic:
                                  type: string
                      customization: # Parameters to add component customization
                        type: array
                        items:
                          type: string
                      permanent:
                        type: boolean
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
                deploy:
                  type: boolean
            status:
              type: object
              properties:
                replicas:
                  type: integer
                components:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      status:
                        type: string
                ready:
                  type: string
      additionalPrinterColumns:
        - jsonPath: .spec.replicas
          name: Desired Replicas
          type: integer
          priority: 0
        - jsonPath: .status.replicas
          name: Current Replicas
          type: integer
          priority: 0
        - jsonPath: .status.ready
          name: Ready
          type: string
          description: Readiness of the created resource
          priority: 0
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          priority: 0
      #        - jsonPath: .spec.componentes[*].name
      #          name: Image
      #          description: Docker image of the component
      #          type: string
      #          priority: 1 # si es prioridad mayor que 1 aparece solo en la vista amplicada (-o wide)
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
    - name: v1alpha1
      served: false
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                components:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
    - name: v1alpha2
      served: false
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [components,image,replicas]
              properties:
                components:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status:
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
    - name: v1alpha3
      served: false
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [components,replicas]
              properties:
                components:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      previous:
                        type: string
                      next:
                        type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status:
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas


  scope: Namespaced
  names:
    plural: applications
    singular: application
    kind: Application
    shortNames:
      - app